spring.application.name=PdfToExcel
# Increase file upload size (example: 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=${PORT:8080}

#Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/Login
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.hibernate.ddl-auto=update

#Server
spring.datasource.url=jdbc:postgresql://dpg-d6j91dffte5s73dbr750-a.virginia-postgres.render.com:5432/pdfextractdb
spring.datasource.username=pdfextractdb_user
spring.datasource.password=fPnGJ3NSVn5PQZE8TSbs0p7vOjXAYc8R
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

